# Carregando .ARFF

In [ ]:
from scipy.io.arff import loadarff
import numpy as np
import pandas as pd

In [ ]:
data, meta = loadarff('/content/supermarket.arff')
data_np = np.array(data)

df = pd.DataFrame(data_np, dtype = str)
df.to_csv('supermarket.csv', index=False)
df

,department1,department2,department3,department4,department5,department6,department7,department8,department9,grocery misc,...,department208,department209,department210,department211,department212,department213,department214,department215,department216,total
0,?,?,?,?,?,?,?,?,?,?,...,?,?,?,?,?,?,?,?,?,high
1,t,?,?,?,?,?,?,?,?,?,...,?,?,?,?,?,?,?,?,?,low
2,?,?,?,?,?,?,?,?,?,?,...,?,?,?,?,?,?,?,?,?,low
3,t,?,?,?,?,?,?,?,?,?,...,?,?,?,?,?,?,?,?,?,low
4,?,?,?,?,?,?,?,?,?,?,...,?,?,?,?,?,?,?,?,?,low
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4622,?,?,?,?,?,?,?,?,?,?,...,?,?,?,?,?,?,?,?,?,low
4623,?,?,?,t,?,?,?,?,?,?,...,?,?,?,?,?,?,?,?,?,high
4624,?,?,?,?,?,?,?,?,?,?,...,?,?,?,?,?,?,?,?,?,low
4625,?,?,?,?,?,?,?,?,?,?,...,?,?,?,?,?,?,?,?,?,low
4626,t,?,?,?,?,?,?,?,?,?,...,?,?,?,?,?,?,?,?,?,high

In [ ]:
df_nan = pd.read_csv('/content/supermarket.csv', na_values=['?'])
df_nan

/tmp/ipykernel_11011/4082227965.py:1: DtypeWarning: Columns (5,10,77,140) have mixed types. Specify dtype option on import or set low_memory=False.
  df_nan = pd.read_csv('/content/supermarket.csv', na_values=['?'])

,department1,department2,department3,department4,department5,department6,department7,department8,department9,grocery misc,...,department208,department209,department210,department211,department212,department213,department214,department215,department216,total
0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,high
1,t,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,low
2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,low
3,t,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,low
4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,low
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4622,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,low
4623,NaN,NaN,NaN,t,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,high
4624,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,low
4625,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,low
4626,t,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,high

In [ ]:
info_counts = df_nan.info(verbose=True, show_counts=True)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4627 entries, 0 to 4626
Data columns (total 217 columns):
 #    Column              Non-Null Count  Dtype
---   ------              --------------  -----
 0    department1         1047 non-null   object
 1    department2         131 non-null    object
 2    department3         90 non-null     object
 3    department4         84 non-null     object
 4    department5         175 non-null    object
 5    department6         2 non-null      object
 6    department7         67 non-null     object
 7    department8         0 non-null      float64
 8    department9         82 non-null     object
 9    grocery misc        178 non-null    object
 10   department11        5 non-null      object
 11   baby needs          619 non-null    object
 12   bread and cake      3330 non-null   object
 13   baking needs        2795 non-null   object
 14   coupons             0 non-null      float64
 15   juice-sat-cord-ms   2463 non-null   object
 16   tea                 896 non-null    object
 17   biscuits            2605 non-null   object
 18   canned fish-meat    941 non-null    object
 19   canned fruit        1283 non-null   object
 20   canned vegetables   1577 non-null   object
 21   breakfast food      1862 non-null   object
 22   cigs-tobacco pkts   699 non-null    object
 23   cigarette cartons   37 non-null     object
 24   cleaners-polishers  1262 non-null   object
 25   coffee              1094 non-null   object
 26   sauces-gravy-pkle   2201 non-null   object
 27   confectionary       1690 non-null   object
 28   puddings-deserts    788 non-null    object
 29   dishcloths-scour    362 non-null    object
 30   deod-disinfectant   379 non-null    object
 31   frozen foods        2717 non-null   object
 32   razor blades        200 non-null    object
 33   fuels-garden aids   169 non-null    object
 34   spices              359 non-null    object
 35   jams-spreads        1278 non-null   object
 36   insecticides        485 non-null    object
 37   pet foods           1867 non-null   object
 38   laundry needs       1563 non-null   object
 39   party snack foods   2330 non-null   object
 40   tissues-paper prd   2247 non-null   object
 41   wrapping            1336 non-null   object
 42   dried vegetables    29 non-null     object
 43   pkt-canned soup     453 non-null    object
 44   soft drinks         1888 non-null   object
 45   health food other   341 non-null    object
 46   beverages hot       455 non-null    object
 47   health&beauty misc  78 non-null     object
 48   deodorants-soap     1078 non-null   object
 49   mens toiletries     259 non-null    object
 50   medicines           204 non-null    object
 51   haircare            846 non-null    object
 52   dental needs        1064 non-null   object
 53   lotions-creams      294 non-null    object
 54   sanitary pads       416 non-null    object
 55   cough-cold-pain     362 non-null    object
 56   department57        0 non-null      float64
 57   meat misc           131 non-null    object
 58   cheese              1879 non-null   object
 59   chickens            21 non-null     object
 60   milk-cream          2939 non-null   object
 61   cold-meats          672 non-null    object
 62   deli gourmet        208 non-null    object
 63   margarine           2288 non-null   object
 64   salads              6 non-null      object
 65   small goods         1116 non-null   object
 66   dairy foods         1669 non-null   object
 67   fruit drinks        32 non-null     object
 68   delicatessen misc   108 non-null    object
 69   department70        0 non-null      float64
 70   beef                1739 non-null   object
 71   hogget              95 non-null     object
 72   lamb                473 non-null    object
 73   pet food            533 non-null    object
 74   pork                345 non-null    object
 75   poultry             739 non-null    object
 76   veal                91 non-null     object
 77   gourmet meat        2 non-null      object
 78   department79        390 non-null    object
 79   department80        156 non-null    object
 80   department81        0 non-null      float64
 81   produce misc        243 non-null    object
 82   fruit               2962 non-null   object
 83   plants              29 non-null     object
 84   potatoes            734 non-null    object
 85   vegetables          2961 non-null   object
 86   flowers             0 non-null      float64
 87   department88        0 non-null      float64
 88   department89        0 non-null      float64
 89   variety misc        319 non-null    object
 90   brushware           109 non-null    object
 91   electrical          514 non-null    object
 92   haberdashery        45 non-null     object
 93   kitchen             326 non-null    object
 94   manchester          173 non-null    object
 95   pantyhose           43 non-null     object
 96   plasticware         69 non-null     object
 97   department98        0 non-null      float64
 98   stationary          1457 non-null   object
 99   department100       0 non-null      float64
 100  department101       0 non-null      float64
 101  department102       0 non-null      float64
 102  prepared meals      1271 non-null   object
 103  preserving needs    56 non-null     object
 104  condiments          263 non-null    object
 105  cooking oils        478 non-null    object
 106  department107       0 non-null      float64
 107  department108       0 non-null      float64
 108  department109       0 non-null      float64
 109  department110       0 non-null      float64
 110  department111       0 non-null      float64
 111  department112       0 non-null      float64
 112  department113       0 non-null      float64
 113  department114       0 non-null      float64
 114  health food bulk    0 non-null      float64
 115  department116       0 non-null      float64
 116  department117       0 non-null      float64
 117  department118       0 non-null      float64
 118  department119       0 non-null      float64
 119  department120       0 non-null      float64
 120  bake off products   562 non-null    object
 121  department122       1112 non-null   object
 122  department123       39 non-null     object
 123  department124       95 non-null     object
 124  department125       0 non-null      float64
 125  department126       0 non-null      float64
 126  department127       0 non-null      float64
 127  department128       0 non-null      float64
 128  department129       0 non-null      float64
 129  department130       329 non-null    object
 130  small goods2        962 non-null    object
 131  offal               99 non-null     object
 132  mutton              23 non-null     object
 133  trim pork           127 non-null    object
 134  trim lamb           46 non-null     object
 135  imported cheese     233 non-null    object
 136  department137       1854 non-null   object
 137  department138       0 non-null      float64
 138  department139       0 non-null      float64
 139  department140       0 non-null      float64
 140  department141       10 non-null     object
 141  department142       0 non-null      float64
 142  department143       0 non-null      float64
 143  department144       0 non-null      float64
 144  department145       0 non-null      float64
 145  department146       0 non-null      float64
 146  department147       0 non-null      float64
 147  department148       0 non-null      float64
 148  department149       0 non-null      float64
 149  department150       0 non-null      float64
 150  department151       0 non-null      float64
 151  department152       0 non-null      float64
 152  department153       0 non-null      float64
 153  department154       0 non-null      float64
 154  department155       0 non-null      float64
 155  department156       0 non-null      float64
 156  department157       0 non-null      float64
 157  department158       0 non-null      float64
 158  department159       0 non-null      float64
 159  department160       0 non-null      float64
 160  department161       0 non-null      float64
 161  department162       0 non-null      float64
 162  department163       0 non-null      float64
 163  department164       0 non-null      float64
 164  department165       0 non-null      float64
 165  department166       0 non-null      float64
 166  department167       0 non-null      float64
 167  department168       0 non-null      float64
 168  department169       0 non-null      float64
 169  department170       0 non-null      float64
 170  department171       0 non-null      float64
 171  department172       0 non-null      float64
 172  department173       0 non-null      float64
 173  department174       0 non-null      float64
 174  department175       0 non-null      float64
 175  department176       0 non-null      float64
 176  department177       0 non-null      float64
 177  department178       0 non-null      float64
 178  department179       0 non-null      float64
 179  casks white wine    174 non-null    object
 180  casks red wine      51 non-null     object
 181  750ml white nz      281 non-null    object
 182  750ml red nz        91 non-null     object
 183  750ml white imp     99 non-null     object
 184  750ml red imp       97 non-null     object
 185  sparkling nz        129 non-null    object
 186  sparkling imp       23 non-null     object
 187  brew kits/accesry   0 non-null      float64
 188  department189       0 non-null      float64
 189  port and sherry     25 non-null     object
 190  ctrled label wine   0 non-null      float64
 191  department192       0 non-null      float64
 192  department193       10 non-null     object
 193  department194       0 non-null      float64
 194  department195       0 non-null      float64
 195  department196       0 non-null      float64
 196  department197       0 non-null      float64
 197  department198       0 non-null      float64
 198  department199       0 non-null      float64
 199  non host support    87 non-null     object
 200  department201       0 non-null      float64
 201  department202       0 non-null      float64
 202  department203       0 non-null      float64
 203  department204       0 non-null      float64
 204  department205       0 non-null      float64
 205  department206       0 non-null      float64
 206  department207       0 non-null      float64
 207  department208       0 non-null      float64
 208  department209       0 non-null      float64
 209  department210       191 non-null    object
 210  department211       207 non-null    object
 211  department212       38 non-null     object
 212  department213       22 non-null     object
 213  department214       0 non-null      float64
 214  department215       0 non-null      float64
 215  department216       0 non-null      float64
 216  total               4627 non-null   object
dtypes: float64(94), object(123)
memory usage: 7.7+ MB

In [ ]:
df_nan.department7.isna().all()

np.False_

In [ ]:
colunas_removerf = []
i = 0

while (i < len(df_nan.columns)):

    if (df_nan.iloc[:, i].isna().all() == np.True_):
        colunas_removerf.append(df_nan.columns[i])


    i = i + 1

print(colunas_removerf)

df_filtrado = df_nan.drop(colunas_removerf, axis=1)
df_filtrado

['department8', 'coupons', 'department57', 'department70', 'department81', 'flowers', 'department88', 'department89', 'department98', 'department100', 'department101', 'department102', 'department107', 'department108', 'department109', 'department110', 'department111', 'department112', 'department113', 'department114', 'health food bulk', 'department116', 'department117', 'department118', 'department119', 'department120', 'department125', 'department126', 'department127', 'department128', 'department129', 'department138', 'department139', 'department140', 'department142', 'department143', 'department144', 'department145', 'department146', 'department147', 'department148', 'department149', 'department150', 'department151', 'department152', 'department153', 'department154', 'department155', 'department156', 'department157', 'department158', 'department159', 'department160', 'department161', 'department162', 'department163', 'department164', 'department165', 'department166', 'department167', 'department168', 'department169', 'department170', 'department171', 'department172', 'department173', 'department174', 'department175', 'department176', 'department177', 'department178', 'department179', 'brew kits/accesry', 'department189', 'ctrled label wine', 'department192', 'department194', 'department195', 'department196', 'department197', 'department198', 'department199', 'department201', 'department202', 'department203', 'department204', 'department205', 'department206', 'department207', 'department208', 'department209', 'department214', 'department215', 'department216']

,department1,department2,department3,department4,department5,department6,department7,department9,grocery misc,department11,...,sparkling nz,sparkling imp,port and sherry,department193,non host support,department210,department211,department212,department213,total
0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,high
1,t,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,low
2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,low
3,t,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,low
4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,low
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4622,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,low
4623,NaN,NaN,NaN,t,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,high
4624,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,low
4625,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,low
4626,t,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,high

In [ ]:
colunas = df_filtrado.columns
colunas_remover1 = []
i = 0

while i < len(colunas):
    coluna_atual = colunas[i]

    if coluna_atual.startswith('depart'):
        colunas_remover1.append(coluna_atual)


    i = i + 1

print(colunas_remover1)

df_t= df_filtrado.drop(colunas_remover1, axis=1)
df_t

['department1', 'department2', 'department3', 'department4', 'department5', 'department6', 'department7', 'department9', 'department11', 'department79', 'department80', 'department122', 'department123', 'department124', 'department130', 'department137', 'department141', 'department193', 'department210', 'department211', 'department212', 'department213']

,grocery misc,baby needs,bread and cake,baking needs,juice-sat-cord-ms,tea,biscuits,canned fish-meat,canned fruit,canned vegetables,...,casks red wine,750ml white nz,750ml red nz,750ml white imp,750ml red imp,sparkling nz,sparkling imp,port and sherry,non host support,total
0,NaN,t,t,t,t,NaN,t,NaN,NaN,t,...,NaN,t,NaN,NaN,NaN,NaN,NaN,NaN,NaN,high
1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,t,t,t,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,low
2,NaN,NaN,t,t,t,NaN,t,NaN,t,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,low
3,NaN,NaN,t,t,t,NaN,t,NaN,NaN,t,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,low
4,NaN,NaN,t,t,t,t,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,low
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4622,NaN,NaN,t,t,t,NaN,t,NaN,t,t,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,low
4623,NaN,NaN,t,t,t,NaN,t,NaN,t,t,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,high
4624,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,low
4625,NaN,t,NaN,t,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,low
4626,NaN,NaN,t,NaN,t,NaN,t,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,high

In [ ]:
df_t.info(verbose=True, show_counts=True)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4627 entries, 0 to 4626
Data columns (total 101 columns):
 #    Column              Non-Null Count  Dtype
---   ------              --------------  -----
 0    grocery misc        178 non-null    object
 1    baby needs          619 non-null    object
 2    bread and cake      3330 non-null   object
 3    baking needs        2795 non-null   object
 4    juice-sat-cord-ms   2463 non-null   object
 5    tea                 896 non-null    object
 6    biscuits            2605 non-null   object
 7    canned fish-meat    941 non-null    object
 8    canned fruit        1283 non-null   object
 9    canned vegetables   1577 non-null   object
 10   breakfast food      1862 non-null   object
 11   cigs-tobacco pkts   699 non-null    object
 12   cigarette cartons   37 non-null     object
 13   cleaners-polishers  1262 non-null   object
 14   coffee              1094 non-null   object
 15   sauces-gravy-pkle   2201 non-null   object
 16   confectionary       1690 non-null   object
 17   puddings-deserts    788 non-null    object
 18   dishcloths-scour    362 non-null    object
 19   deod-disinfectant   379 non-null    object
 20   frozen foods        2717 non-null   object
 21   razor blades        200 non-null    object
 22   fuels-garden aids   169 non-null    object
 23   spices              359 non-null    object
 24   jams-spreads        1278 non-null   object
 25   insecticides        485 non-null    object
 26   pet foods           1867 non-null   object
 27   laundry needs       1563 non-null   object
 28   party snack foods   2330 non-null   object
 29   tissues-paper prd   2247 non-null   object
 30   wrapping            1336 non-null   object
 31   dried vegetables    29 non-null     object
 32   pkt-canned soup     453 non-null    object
 33   soft drinks         1888 non-null   object
 34   health food other   341 non-null    object
 35   beverages hot       455 non-null    object
 36   health&beauty misc  78 non-null     object
 37   deodorants-soap     1078 non-null   object
 38   mens toiletries     259 non-null    object
 39   medicines           204 non-null    object
 40   haircare            846 non-null    object
 41   dental needs        1064 non-null   object
 42   lotions-creams      294 non-null    object
 43   sanitary pads       416 non-null    object
 44   cough-cold-pain     362 non-null    object
 45   meat misc           131 non-null    object
 46   cheese              1879 non-null   object
 47   chickens            21 non-null     object
 48   milk-cream          2939 non-null   object
 49   cold-meats          672 non-null    object
 50   deli gourmet        208 non-null    object
 51   margarine           2288 non-null   object
 52   salads              6 non-null      object
 53   small goods         1116 non-null   object
 54   dairy foods         1669 non-null   object
 55   fruit drinks        32 non-null     object
 56   delicatessen misc   108 non-null    object
 57   beef                1739 non-null   object
 58   hogget              95 non-null     object
 59   lamb                473 non-null    object
 60   pet food            533 non-null    object
 61   pork                345 non-null    object
 62   poultry             739 non-null    object
 63   veal                91 non-null     object
 64   gourmet meat        2 non-null      object
 65   produce misc        243 non-null    object
 66   fruit               2962 non-null   object
 67   plants              29 non-null     object
 68   potatoes            734 non-null    object
 69   vegetables          2961 non-null   object
 70   variety misc        319 non-null    object
 71   brushware           109 non-null    object
 72   electrical          514 non-null    object
 73   haberdashery        45 non-null     object
 74   kitchen             326 non-null    object
 75   manchester          173 non-null    object
 76   pantyhose           43 non-null     object
 77   plasticware         69 non-null     object
 78   stationary          1457 non-null   object
 79   prepared meals      1271 non-null   object
 80   preserving needs    56 non-null     object
 81   condiments          263 non-null    object
 82   cooking oils        478 non-null    object
 83   bake off products   562 non-null    object
 84   small goods2        962 non-null    object
 85   offal               99 non-null     object
 86   mutton              23 non-null     object
 87   trim pork           127 non-null    object
 88   trim lamb           46 non-null     object
 89   imported cheese     233 non-null    object
 90   casks white wine    174 non-null    object
 91   casks red wine      51 non-null     object
 92   750ml white nz      281 non-null    object
 93   750ml red nz        91 non-null     object
 94   750ml white imp     99 non-null     object
 95   750ml red imp       97 non-null     object
 96   sparkling nz        129 non-null    object
 97   sparkling imp       23 non-null     object
 98   port and sherry     25 non-null     object
 99   non host support    87 non-null     object
 100  total               4627 non-null   object
dtypes: object(101)
memory usage: 3.6+ MB

In [ ]:
df_t.to_csv('supermarket_filtrado.csv', index=False)